name: shrine
description: Learn the basics of using Material Components by building a simple app with core components.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
  uses-material-design: true
  assets:
    - assets/manga.png
    # TODO: Add slanted menu asset (104)
    - assets/slanted_menu.png
    - packages/shrine_images/0-0.jpg
    - assets/manga0.png
    - assets/manga1.png
    - assets/manga2.png
    - assets/manga3.png
    - assets/manga4.png
    - assets/manga5.png
    - assets/manga6.png
    - assets/manga7.png
    - assets/manga8.png
    - assets/manga9.png
    - assets/manga10.png
    - assets/manga11.png
    - assets/manga12.png
    - assets/manga13.png
    - assets/manga14.png
    - assets/manga15.png
    - assets/manga16.png
    - assets/manga17.png
    - assets/manga18.png
    - assets/manga19.png
    - assets/manga20.png
    - assets/manga21.png
    - assets/manga22.png
    - assets/manga23.png
    - assets/manga24.png
    - assets/manga25.png
    - assets/manga26.png
    - assets/manga27.png
    - assets/manga28.png
    - assets/manga29.png
    - assets/manga30.png
    - assets/manga31.png
    - assets/manga32.png
    - assets/manga33.png
    - assets/manga34.png
    - assets/manga35.png
    - assets/manga36.png
    - assets/manga37.png
